apiVersion: v1
kind: Namespace
metadata:
  name: raguard-dev
  labels:
    app.kubernetes.io/name: veritas-rag
    app.kubernetes.io/managed-by: manual
---
apiVersion: v1
kind: Namespace
metadata:
  name: veritas-rag-staging
  labels:
    app.kubernetes.io/name: veritas-rag
    app.kubernetes.io/managed-by: manual
---
apiVersion: v1
kind: Namespace
metadata:
  name: veritas-rag-production
  labels:
    app.kubernetes.io/name: veritas-rag
    app.kubernetes.io/managed-by: manual
