"""Schemas for the Query Analytics module."""

from .analytics_dto import (
    AnalyticsFilterDTO,
    ConfidenceAnalyticsDTO,
    LatencyAnalyticsDTO,
    QueryHistoryItemDTO,
    QueryHistoryListDTO,
    QueryTrendsDTO,
    ReliabilityHistoryDTO,
    SearchAnalyticsDTO,
    SuccessRateDTO,
    StageTraceDTO,
    RetrievalCandidateTraceDTO,
    ConfidenceSignalTraceDTO,
    SelfCorrectionTraceDTO,
    QueryTraceDetailDTO,
    QuerySandboxRequestDTO,
    QuerySandboxResponseDTO,
)
from .errors import (
    AnalyticsDomainException,
    AnalyticsErrorCode,
    AggregationFailed,
    InvalidDateRange,
    RecordNotFound,
)
from .reporting_dto import (
    ReportType,
    ReportFormat,
    ReportExportRequestDTO,
    ReportMetadataDTO,
)

__all__ = [
    "AggregationFailed",
    "AnalyticsDomainException",
    "AnalyticsErrorCode",
    "AnalyticsFilterDTO",
    "ConfidenceAnalyticsDTO",
    "InvalidDateRange",
    "LatencyAnalyticsDTO",
    "QueryHistoryItemDTO",
    "QueryHistoryListDTO",
    "QueryTrendsDTO",
    "RecordNotFound",
    "ReliabilityHistoryDTO",
    "SearchAnalyticsDTO",
    "SuccessRateDTO",
    "StageTraceDTO",
    "RetrievalCandidateTraceDTO",
    "ConfidenceSignalTraceDTO",
    "SelfCorrectionTraceDTO",
    "QueryTraceDetailDTO",
    "QuerySandboxRequestDTO",
    "QuerySandboxResponseDTO",
    "ReportType",
    "ReportFormat",
    "ReportExportRequestDTO",
    "ReportMetadataDTO",
]
