"""Add tenant_id and workspace_name to users

Revision ID: 0021_add_tenant_id_workspace_name
Revises: 0020_production_hardening_schema
Create Date: 2026-07-22 07:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0021'
down_revision = '0020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('workspace_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'workspace_name')
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###
