"""remove_supabase_user_id

Revision ID: bb700f84136d
Revises: 113748cb0671
Create Date: 2026-08-07 13:36:17.137760+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb700f84136d'
down_revision: Union[str, None] = '113748cb0671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_job_diagnostics',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('failing_step', sa.String(length=100), nullable=False),
    sa.Column('exception_class', sa.String(length=255), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('worker_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remediation_status', sa.String(length=50), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_failed_job_diagnostics_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_job_diagnostics'))
    )
    op.create_index(op.f('ix_failed_job_diagnostics_job_id'), 'failed_job_diagnostics', ['job_id'], unique=False)
    op.create_index(op.f('ix_failed_job_diagnostics_remediation_status'), 'failed_job_diagnostics', ['remediation_status'], unique=False)
    op.create_index(op.f('ix_failed_job_diagnostics_tenant_id'), 'failed_job_diagnostics', ['tenant_id'], unique=False)
    op.create_index('ix_failed_jobs_job_step', 'failed_job_diagnostics', ['job_id', 'failing_step'], unique=False)
    op.create_index('ix_failed_jobs_tenant_remediation', 'failed_job_diagnostics', ['tenant_id', 'remediation_status'], unique=False)
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_column('users', 'supabase_user_id')
    op.drop_index(op.f('ix_vector_reindex_jobs_id'), table_name='vector_reindex_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vector_reindex_jobs_id'), 'vector_reindex_jobs', ['id'], unique=False)
    op.add_column('users', sa.Column('supabase_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.drop_index('ix_failed_jobs_tenant_remediation', table_name='failed_job_diagnostics')
    op.drop_index('ix_failed_jobs_job_step', table_name='failed_job_diagnostics')
    op.drop_index(op.f('ix_failed_job_diagnostics_tenant_id'), table_name='failed_job_diagnostics')
    op.drop_index(op.f('ix_failed_job_diagnostics_remediation_status'), table_name='failed_job_diagnostics')
    op.drop_index(op.f('ix_failed_job_diagnostics_job_id'), table_name='failed_job_diagnostics')
    op.drop_table('failed_job_diagnostics')
    # ### end Alembic commands ###
