"""add_user_profile_settings

Revision ID: 5de17c10bdc3
Revises: 0224febbe7cc
Create Date: 2026-07-24 09:37:51.211203+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5de17c10bdc3'
down_revision: Union[str, None] = '0224febbe7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('workspace_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'workspace_settings')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'profile_data')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
