"""add workspace_name

Revision ID: 42e18ea087d3
Revises: 76b691b69868
Create Date: 2026-08-18 03:14:30.675623+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42e18ea087d3'
down_revision: Union[str, None] = '76b691b69868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('workspace_name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'workspace_id')
    op.add_column('workspace_webhooks', sa.Column('secret_hash', sa.String(length=255), nullable=False))
    op.add_column('workspace_webhooks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('workspace_webhooks', 'endpoint_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.execute('ALTER TABLE workspace_webhooks ALTER COLUMN events TYPE JSONB USING array_to_json(events)::jsonb')
    op.alter_column('workspace_webhooks', 'tenant_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               postgresql_using='tenant_id::uuid',
               existing_nullable=False)
    op.drop_column('workspace_webhooks', 'secret_key_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_webhooks', sa.Column('secret_key_encrypted', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('workspace_webhooks', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('workspace_webhooks', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('workspace_webhooks', 'endpoint_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('workspace_webhooks', 'is_deleted')
    op.drop_column('workspace_webhooks', 'secret_hash')
    op.add_column('users', sa.Column('workspace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'workspace_name')
    op.add_column('notification_delivery_logs', sa.Column('notification_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('notification_delivery_logs', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('notification_delivery_logs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notification_delivery_logs', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED_TRANSIENT', 'FAILED_PERMANENT', name='delivery_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('notification_delivery_logs', 'target',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notification_delivery_logs', 'type',
               existing_type=sa.Enum('EMAIL', 'WEBHOOK', name='notification_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('notification_delivery_logs', 'tenant_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('notification_delivery_logs', 'is_deleted')
    op.drop_column('notification_delivery_logs', 'attempt_count')
    op.drop_column('notification_delivery_logs', 'payload_snapshot')
    # ### end Alembic commands ###
