"""add_f5_3_f5_4_folder_columns

Revision ID: a7ea1886faaa
Revises: ee4c9b873bce
Create Date: 2026-08-03 01:00:29.779013+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7ea1886faaa'
down_revision: Union[str, None] = 'ee4c9b873bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('cascade_status', sa.String(length=30), nullable=True))
    op.add_column('folders', sa.Column('purge_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('folders', sa.Column('purge_status', sa.String(length=20), nullable=True))
    op.add_column('folders', sa.Column('purge_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('folders', sa.Column('purge_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('folders', sa.Column('purge_worker_task_id', sa.Text(), nullable=True))
    op.create_index('ix_folders_purge_scheduled', 'folders', ['workspace_id', 'purge_at'], unique=False, postgresql_where="purge_status = 'scheduled' AND is_deleted = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_folders_purge_scheduled', table_name='folders', postgresql_where="purge_status = 'scheduled' AND is_deleted = true")
    op.drop_column('folders', 'purge_worker_task_id')
    op.drop_column('folders', 'purge_completed_at')
    op.drop_column('folders', 'purge_started_at')
    op.drop_column('folders', 'purge_status')
    op.drop_column('folders', 'purge_at')
    op.drop_column('folders', 'cascade_status')
    # ### end Alembic commands ###
