"""f2.7_sso_and_f2.8_refresh

Revision ID: 6db89769cb3e
Revises: c3d4e5f6a1b2
Create Date: 2026-07-31 10:40:42.662088+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6db89769cb3e'
down_revision: Union[str, None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sso_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sso_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sso_identities')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index(op.f('ix_sso_identities_provider'), 'sso_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_sso_identities_provider_user_id'), 'sso_identities', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_sso_identities_user_id'), 'sso_identities', ['user_id'], unique=False)
    op.add_column('user_sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('device', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'device')
    op.drop_column('user_sessions', 'rotated_at')
    op.drop_column('user_sessions', 'last_used_at')
    op.drop_index(op.f('ix_sso_identities_user_id'), table_name='sso_identities')
    op.drop_index(op.f('ix_sso_identities_provider_user_id'), table_name='sso_identities')
    op.drop_index(op.f('ix_sso_identities_provider'), table_name='sso_identities')
    op.drop_table('sso_identities')
    # ### end Alembic commands ###
