"""Add metadata and bulk batch schemas

Revision ID: fb78d3583737
Revises: 1e14a3b38d04
Create Date: 2026-08-03 08:00:10.928427+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb78d3583737'
down_revision: Union[str, None] = '1e14a3b38d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_batches',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_bulk_batches_created_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_batches'))
    )
    op.create_index(op.f('ix_bulk_batches_created_by_user_id'), 'bulk_batches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_batches_status'), 'bulk_batches', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_batches_tenant_id'), 'bulk_batches', ['tenant_id'], unique=False)
    op.add_column('documents', sa.Column('user_metadata', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_index(op.f('ix_folders_path'), table_name='folders', postgresql_ops={'path': 'gist_trgm_ops'}, postgresql_using='gist')
    op.alter_column('identity_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('identity_providers', 'certificates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('identity_providers', 'attribute_mapping',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('identity_providers', 'jit_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('identity_providers', 'force_sso',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('processing_jobs', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_processing_jobs_batch_id'), 'processing_jobs', ['batch_id'], unique=False)
    op.create_foreign_key(op.f('fk_processing_jobs_batch_id_bulk_batches'), 'processing_jobs', 'bulk_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.alter_column('workspace_domains', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_workspace_domains_domain'), table_name='workspace_domains', postgresql_where="((status)::text = 'VERIFIED'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspace_domains_domain'), 'workspace_domains', ['domain_name'], unique=True, postgresql_where="((status)::text = 'VERIFIED'::text)")
    op.alter_column('workspace_domains', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_processing_jobs_batch_id_bulk_batches'), 'processing_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_processing_jobs_batch_id'), table_name='processing_jobs')
    op.drop_column('processing_jobs', 'batch_id')
    op.alter_column('identity_providers', 'force_sso',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('identity_providers', 'jit_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('identity_providers', 'attribute_mapping',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('identity_providers', 'certificates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('identity_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_folders_path'), 'folders', ['path'], unique=False, postgresql_ops={'path': 'gist_trgm_ops'}, postgresql_using='gist')
    op.drop_column('documents', 'user_metadata')
    op.drop_index(op.f('ix_bulk_batches_tenant_id'), table_name='bulk_batches')
    op.drop_index(op.f('ix_bulk_batches_status'), table_name='bulk_batches')
    op.drop_index(op.f('ix_bulk_batches_created_by_user_id'), table_name='bulk_batches')
    op.drop_table('bulk_batches')
    # ### end Alembic commands ###
