"""f6_1_processing_job_queue

Revision ID: b13467ec7b6b
Revises: fb78d3583737
Create Date: 2026-08-03 08:39:13.626706+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b13467ec7b6b'
down_revision: Union[str, None] = 'fb78d3583737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_job_audit_logs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_processing_job_audit_logs_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_job_audit_logs'))
    )
    op.create_index('ix_job_audit_job_event', 'processing_job_audit_logs', ['job_id', 'event'], unique=False)
    op.create_index('ix_job_audit_job_timestamp', 'processing_job_audit_logs', ['job_id', 'timestamp'], unique=False)
    op.create_table('processing_job_steps',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_processing_job_steps_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_job_steps'))
    )
    op.create_index('ix_job_steps_job_status', 'processing_job_steps', ['job_id', 'step_status'], unique=False)
    op.create_index('ix_job_steps_job_step', 'processing_job_steps', ['job_id', 'step_name'], unique=False)
    op.add_column('processing_jobs', sa.Column('priority', sa.Integer(), nullable=True))
    op.execute("UPDATE processing_jobs SET priority = 1")
    op.alter_column('processing_jobs', 'priority', nullable=False)
    op.add_column('processing_jobs', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_jobs', sa.Column('claimed_by_worker', sa.String(length=255), nullable=True))
    op.add_column('processing_jobs', sa.Column('step_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('processing_jobs', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('processing_jobs', sa.Column('dlq_reason', sa.Text(), nullable=True))
    op.add_column('processing_jobs', sa.Column('dlq_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_jobs', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_jobs', sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True))
    op.add_column('processing_jobs', sa.Column('resume_from_step', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_processing_jobs_idempotency_key'), 'processing_jobs', ['idempotency_key'], unique=True)
    op.create_foreign_key(op.f('fk_processing_jobs_cancelled_by_user_id_users'), 'processing_jobs', 'users', ['cancelled_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_processing_jobs_cancelled_by_user_id_users'), 'processing_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_processing_jobs_idempotency_key'), table_name='processing_jobs')
    op.drop_column('processing_jobs', 'resume_from_step')
    op.drop_column('processing_jobs', 'cancelled_by_user_id')
    op.drop_column('processing_jobs', 'cancelled_at')
    op.drop_column('processing_jobs', 'dlq_at')
    op.drop_column('processing_jobs', 'dlq_reason')
    op.drop_column('processing_jobs', 'idempotency_key')
    op.drop_column('processing_jobs', 'step_metrics')
    op.drop_column('processing_jobs', 'claimed_by_worker')
    op.drop_column('processing_jobs', 'claimed_at')
    op.drop_column('processing_jobs', 'scheduled_at')
    op.drop_column('processing_jobs', 'priority')
    op.drop_index('ix_job_steps_job_step', table_name='processing_job_steps')
    op.drop_index('ix_job_steps_job_status', table_name='processing_job_steps')
    op.drop_table('processing_job_steps')
    op.drop_index('ix_job_audit_job_timestamp', table_name='processing_job_audit_logs')
    op.drop_index('ix_job_audit_job_event', table_name='processing_job_audit_logs')
    op.drop_table('processing_job_audit_logs')
    # ### end Alembic commands ###
