"""f6_2_ocr_fields

Revision ID: 5e96192505b8
Revises: b13467ec7b6b
Create Date: 2026-08-03 08:47:06.788533+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e96192505b8'
down_revision: Union[str, None] = 'b13467ec7b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('requires_ocr', sa.Boolean(), nullable=True))
    op.execute("UPDATE document_versions SET requires_ocr = false")
    op.alter_column('document_versions', 'requires_ocr', nullable=False)
    op.add_column('document_versions', sa.Column('ocr_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'ocr_languages')
    op.drop_column('document_versions', 'requires_ocr')
    # ### end Alembic commands ###
