"""Add relative_path to document

Revision ID: 0224febbe7cc
Revises: 680b30cdb5dd
Create Date: 2026-07-24 05:28:44.929921+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0224febbe7cc'
down_revision: Union[str, None] = '680b30cdb5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_runs_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_fault_policies_chaos_token'), table_name='fault_policies')
    op.drop_table('fault_policies')
    op.drop_index(op.f('ix_self_healing_policies_tenant_id'), table_name='self_healing_policies')
    op.drop_table('self_healing_policies')
    op.drop_index(op.f('ix_validation_logs_correlation_id'), table_name='validation_logs')
    op.drop_index(op.f('ix_validation_logs_tenant_id'), table_name='validation_logs')
    op.drop_table('validation_logs')
    op.drop_index(op.f('ix_alert_history_tenant_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_golden_datasets_tenant_id'), table_name='golden_datasets')
    op.drop_table('golden_datasets')
    op.drop_index(op.f('idx_retry_decision_logs_query_id'), table_name='retry_decision_logs')
    op.drop_index(op.f('idx_retry_decision_logs_tenant_action'), table_name='retry_decision_logs')
    op.drop_index(op.f('ix_retry_decision_logs_tenant_id'), table_name='retry_decision_logs')
    op.drop_table('retry_decision_logs')
    op.drop_index(op.f('ix_health_logs_tenant_id'), table_name='health_logs')
    op.drop_table('health_logs')
    op.drop_index(op.f('ix_token_usages_correlation_id'), table_name='token_usages')
    op.drop_index(op.f('ix_token_usages_tenant_id'), table_name='token_usages')
    op.drop_table('token_usages')
    op.drop_index(op.f('idx_confidence_evaluations_tenant_id'), table_name='confidence_evaluations')
    op.drop_table('confidence_evaluations')
    op.drop_table('tenant_quotas')
    op.drop_index(op.f('ix_reflection_logs_correlation_id'), table_name='reflection_logs')
    op.drop_index(op.f('ix_reflection_logs_tenant_id'), table_name='reflection_logs')
    op.drop_table('reflection_logs')
    op.drop_index(op.f('ix_quarantine_logs_document_id'), table_name='quarantine_logs')
    op.drop_table('quarantine_logs')
    op.drop_index(op.f('ix_healing_actions_log_tenant_id'), table_name='healing_actions_log')
    op.drop_table('healing_actions_log')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_scoring_logs_correlation_id'), table_name='scoring_logs')
    op.drop_index(op.f('ix_scoring_logs_tenant_id'), table_name='scoring_logs')
    op.drop_table('scoring_logs')
    op.create_index(op.f('ix_chunk_embeddings_document_version_id'), 'chunk_embeddings', ['document_version_id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_tenant_doc_ver_idx'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_tenant_hash'), table_name='document_chunks')
    op.add_column('documents', sa.Column('relative_path', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_embedding_jobs_document_version_id'), 'embedding_jobs', ['document_version_id'], unique=False)
    op.drop_index(op.f('ix_health_scan_jobs_tenant_status'), table_name='health_scan_jobs')
    op.drop_column('health_scan_jobs', 'is_deleted')
    op.drop_index(op.f('ix_query_analytics_tenant_id'), table_name='query_analytics_records')
    op.create_index(op.f('ix_query_analytics_records_tenant_id'), 'query_analytics_records', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_stale_embedding_records_tenant_chunk'), table_name='stale_embedding_records')
    op.create_index(op.f('ix_stale_embedding_records_chunk_id'), 'stale_embedding_records', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stale_embedding_records_chunk_id'), table_name='stale_embedding_records')
    op.create_index(op.f('ix_stale_embedding_records_tenant_chunk'), 'stale_embedding_records', ['tenant_id', 'chunk_id'], unique=False)
    op.drop_index(op.f('ix_query_analytics_records_tenant_id'), table_name='query_analytics_records')
    op.create_index(op.f('ix_query_analytics_tenant_id'), 'query_analytics_records', ['tenant_id'], unique=False)
    op.add_column('health_scan_jobs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_health_scan_jobs_tenant_status'), 'health_scan_jobs', ['tenant_id', 'scan_type', 'status'], unique=False)
    op.drop_index(op.f('ix_embedding_jobs_document_version_id'), table_name='embedding_jobs')
    op.drop_column('documents', 'relative_path')
    op.create_index(op.f('ix_document_chunks_tenant_hash'), 'document_chunks', ['tenant_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_tenant_doc_ver_idx'), 'document_chunks', ['tenant_id', 'document_id', 'document_version_id', 'chunk_index'], unique=False)
    op.drop_index(op.f('ix_chunk_embeddings_document_version_id'), table_name='chunk_embeddings')
    op.create_table('scoring_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_trusted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('metadata_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scoring_logs_pkey'))
    )
    op.create_index(op.f('ix_scoring_logs_tenant_id'), 'scoring_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_scoring_logs_correlation_id'), 'scoring_logs', ['correlation_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('operator', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('channels_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cooldown_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_rules_pkey'))
    )
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('healing_actions_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('trigger_reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('changes_applied', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_rolled_back', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('healing_actions_log_pkey'))
    )
    op.create_index(op.f('ix_healing_actions_log_tenant_id'), 'healing_actions_log', ['tenant_id'], unique=False)
    op.create_table('quarantine_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quarantine_logs_pkey'))
    )
    op.create_index(op.f('ix_quarantine_logs_document_id'), 'quarantine_logs', ['document_id'], unique=False)
    op.create_table('reflection_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('overall_verdict', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('hallucination_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completeness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('consistency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_safe_to_serve', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metadata_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reflection_logs_pkey'))
    )
    op.create_index(op.f('ix_reflection_logs_tenant_id'), 'reflection_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reflection_logs_correlation_id'), 'reflection_logs', ['correlation_id'], unique=False)
    op.create_table('tenant_quotas',
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('monthly_token_limit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('monthly_budget_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('warning_threshold_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_hard_enforced', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('tenant_quotas_pkey'))
    )
    op.create_table('confidence_evaluations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('coverage_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('strength_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('freshness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('conflict_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_degraded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('confidence_evaluations_pkey'))
    )
    op.create_index(op.f('idx_confidence_evaluations_tenant_id'), 'confidence_evaluations', ['tenant_id'], unique=False)
    op.create_table('token_usages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_usages_pkey'))
    )
    op.create_index(op.f('ix_token_usages_tenant_id'), 'token_usages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_token_usages_correlation_id'), 'token_usages', ['correlation_id'], unique=False)
    op.create_table('health_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('issues_found_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metadata_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('health_logs_pkey'))
    )
    op.create_index(op.f('ix_health_logs_tenant_id'), 'health_logs', ['tenant_id'], unique=False)
    op.create_table('retry_decision_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('query_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('backoff_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_budget_exhausted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_monotonic_regression', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reason_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('retry_decision_logs_pkey'))
    )
    op.create_index(op.f('ix_retry_decision_logs_tenant_id'), 'retry_decision_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_retry_decision_logs_tenant_action'), 'retry_decision_logs', ['tenant_id', 'action'], unique=False)
    op.create_index(op.f('idx_retry_decision_logs_query_id'), 'retry_decision_logs', ['query_id'], unique=False)
    op.create_table('golden_datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('golden_datasets_pkey'))
    )
    op.create_index(op.f('ix_golden_datasets_tenant_id'), 'golden_datasets', ['tenant_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('channel_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('payload_sent', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('alert_history_rule_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_history_pkey'))
    )
    op.create_index(op.f('ix_alert_history_tenant_id'), 'alert_history', ['tenant_id'], unique=False)
    op.create_table('validation_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('overall_verdict', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('entailment_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unsupported_claim_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invalid_citation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('metadata_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_logs_pkey'))
    )
    op.create_index(op.f('ix_validation_logs_tenant_id'), 'validation_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_validation_logs_correlation_id'), 'validation_logs', ['correlation_id'], unique=False)
    op.create_table('self_healing_policies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('auto_parameter_tuning', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('auto_model_rotation', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('auto_quarantine_sweep', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('max_interventions_per_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('self_healing_policies_pkey'))
    )
    op.create_index(op.f('ix_self_healing_policies_tenant_id'), 'self_healing_policies', ['tenant_id'], unique=False)
    op.create_table('fault_policies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chaos_token', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('fault_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('target_provider', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_rate_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('fault_policies_pkey'))
    )
    op.create_index(op.f('ix_fault_policies_chaos_token'), 'fault_policies', ['chaos_token'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('f1_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('average_reliability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_examples', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluation_runs_pkey'))
    )
    op.create_index(op.f('ix_evaluation_runs_dataset_id'), 'evaluation_runs', ['dataset_id'], unique=False)
    # ### end Alembic commands ###
