"""epic11_notifications

Revision ID: 6c11701a28c5
Revises: bb700f84136d
Create Date: 2026-08-15 07:30:06.045522+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c11701a28c5'
down_revision: Union[str, None] = 'bb700f84136d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_events',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('target_module', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=50), nullable=False),
    sa.Column('new_state', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuit_breaker_events'))
    )
    op.create_index(op.f('ix_circuit_breaker_events_target_module'), 'circuit_breaker_events', ['target_module'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_events_tenant_id'), 'circuit_breaker_events', ['tenant_id'], unique=False)
    op.create_index('ix_circuit_events_tenant_target', 'circuit_breaker_events', ['tenant_id', 'target_module', 'created_at'], unique=False)
    op.create_table('health_scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('orphans_found', sa.Integer(), nullable=False),
    sa.Column('orphans_purged', sa.Integer(), nullable=False),
    sa.Column('stale_chunks_found', sa.Integer(), nullable=False),
    sa.Column('parity_status', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_scan_jobs'))
    )
    op.create_index(op.f('ix_health_scan_jobs_tenant_id'), 'health_scan_jobs', ['tenant_id'], unique=False)
    op.create_table('notification_delivery_logs',
    sa.Column('type', sa.Enum('EMAIL', 'WEBHOOK', name='notification_type_enum'), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED_TRANSIENT', 'FAILED_PERMANENT', name='delivery_status_enum'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery_logs'))
    )
    op.create_index(op.f('ix_notification_delivery_logs_next_retry_at'), 'notification_delivery_logs', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_status'), 'notification_delivery_logs', ['status'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_tenant_id'), 'notification_delivery_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_type'), 'notification_delivery_logs', ['type'], unique=False)
    op.create_table('retrieval_sla_logs',
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('target_module', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('is_degraded_fallback', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_sla_logs'))
    )
    op.create_index(op.f('ix_retrieval_sla_logs_correlation_id'), 'retrieval_sla_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_retrieval_sla_logs_tenant_id'), 'retrieval_sla_logs', ['tenant_id'], unique=False)
    op.create_index('ix_sla_logs_tenant_breach', 'retrieval_sla_logs', ['tenant_id', 'is_sla_breached'], unique=False)
    op.create_index('ix_sla_logs_tenant_created', 'retrieval_sla_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_sla_logs_tenant_degraded', 'retrieval_sla_logs', ['tenant_id', 'is_degraded_fallback'], unique=False)
    op.create_table('vector_reindex_jobs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_alias', sa.String(), nullable=False),
    sa.Column('staging_collection', sa.String(), nullable=False),
    sa.Column('previous_collection', sa.String(), nullable=True),
    sa.Column('target_model', sa.String(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('total_vectors_indexed', sa.Integer(), nullable=False),
    sa.Column('parity_verified', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vector_reindex_jobs'))
    )
    op.create_index(op.f('ix_vector_reindex_jobs_workspace_id'), 'vector_reindex_jobs', ['workspace_id'], unique=False)
    op.create_table('workspace_webhooks',
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_webhooks'))
    )
    op.create_index(op.f('ix_workspace_webhooks_tenant_id'), 'workspace_webhooks', ['tenant_id'], unique=False)
    op.create_table('domain_cooldowns',
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('released_by_workspace_id', sa.UUID(), nullable=False),
    sa.Column('cooldown_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['released_by_workspace_id'], ['workspaces.id'], name=op.f('fk_domain_cooldowns_released_by_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_name', name=op.f('pk_domain_cooldowns'))
    )
    op.create_table('identity_providers',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('entity_id_issuer', sa.String(length=255), nullable=False),
    sa.Column('sso_url', sa.String(length=2048), nullable=False),
    sa.Column('logout_url', sa.String(length=2048), nullable=True),
    sa.Column('metadata_url', sa.String(length=2048), nullable=True),
    sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_restrictions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('jit_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('force_sso', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_identity_providers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_providers'))
    )
    op.create_index(op.f('ix_identity_providers_workspace_id'), 'identity_providers', ['workspace_id'], unique=False)
    op.create_table('workspace_domains',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('verification_token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dns_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_domains_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_domains')),
    sa.UniqueConstraint('verification_token_hash', name=op.f('uq_workspace_domains_verification_token_hash'))
    )
    op.create_index(op.f('ix_workspace_domains_workspace_id'), 'workspace_domains', ['workspace_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('strategy_used', sa.String(length=50), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('previous_chunk_id', sa.UUID(), nullable=True),
    sa.Column('next_chunk_id', sa.UUID(), nullable=True),
    sa.Column('page_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_chunks_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_chunk_id'], ['document_chunks.id'], name=op.f('fk_document_chunks_next_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], name=op.f('fk_document_chunks_parent_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_chunk_id'], ['document_chunks.id'], name=op.f('fk_document_chunks_previous_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_version_id'), 'document_chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_tenant_id'), 'document_chunks', ['tenant_id'], unique=False)
    op.create_table('embedding_jobs',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('failed_chunks', sa.Integer(), nullable=False),
    sa.Column('total_tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('step_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('fallback_provider', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_embedding_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_embedding_jobs_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_jobs'))
    )
    op.create_index(op.f('ix_embedding_jobs_document_id'), 'embedding_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_document_version_id'), 'embedding_jobs', ['document_version_id'], unique=False)
    op.create_index('ix_embedding_jobs_tenant_created_idx', 'embedding_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_embedding_jobs_tenant_doc_ver_idx', 'embedding_jobs', ['tenant_id', 'document_version_id', 'status'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_tenant_id'), 'embedding_jobs', ['tenant_id'], unique=False)
    op.create_table('vector_index_metadata',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('points_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_vector_index_metadata_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_vector_index_metadata_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vector_index_metadata')),
    sa.UniqueConstraint('tenant_id', 'document_version_id', 'collection_name', name='uq_vector_index_tenant_ver_col')
    )
    op.create_index(op.f('ix_vector_index_metadata_document_id'), 'vector_index_metadata', ['document_id'], unique=False)
    op.create_index(op.f('ix_vector_index_metadata_document_version_id'), 'vector_index_metadata', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_vector_index_metadata_tenant_id'), 'vector_index_metadata', ['tenant_id'], unique=False)
    op.create_index('ix_vector_metadata_doc_ver_idx', 'vector_index_metadata', ['document_id', 'document_version_id'], unique=False)
    op.create_index('ix_vector_metadata_tenant_status_idx', 'vector_index_metadata', ['tenant_id', 'status'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_chunk_embeddings_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_embeddings')),
    sa.UniqueConstraint('tenant_id', 'chunk_id', name='uq_chunk_embeddings_tenant_chunk')
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_content_hash'), 'chunk_embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_document_version_id'), 'chunk_embeddings', ['document_version_id'], unique=False)
    op.create_index('ix_chunk_embeddings_tenant_doc_ver_idx', 'chunk_embeddings', ['tenant_id', 'document_version_id'], unique=False)
    op.create_index('ix_chunk_embeddings_tenant_hash_model_idx', 'chunk_embeddings', ['tenant_id', 'content_hash', 'provider', 'model_name'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_tenant_id'), 'chunk_embeddings', ['tenant_id'], unique=False)
    op.create_table('chunk_relationships',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('target_chunk_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_chunk_relationships_source_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_chunk_id'], ['document_chunks.id'], name=op.f('fk_chunk_relationships_target_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_relationships'))
    )
    op.create_index(op.f('ix_chunk_relationships_source_chunk_id'), 'chunk_relationships', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_relationships_target_chunk_id'), 'chunk_relationships', ['target_chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_relationships_tenant_id'), 'chunk_relationships', ['tenant_id'], unique=False)
    op.create_table('stale_embedding_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('old_provider', sa.String(length=50), nullable=False),
    sa.Column('old_model_name', sa.String(length=100), nullable=False),
    sa.Column('target_provider', sa.String(length=50), nullable=False),
    sa.Column('target_model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_stale_embedding_records_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stale_embedding_records'))
    )
    op.create_index(op.f('ix_stale_embedding_records_chunk_id'), 'stale_embedding_records', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_stale_embedding_records_tenant_id'), 'stale_embedding_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stale_embedding_records_tenant_id'), table_name='stale_embedding_records')
    op.drop_index(op.f('ix_stale_embedding_records_chunk_id'), table_name='stale_embedding_records')
    op.drop_table('stale_embedding_records')
    op.drop_index(op.f('ix_chunk_relationships_tenant_id'), table_name='chunk_relationships')
    op.drop_index(op.f('ix_chunk_relationships_target_chunk_id'), table_name='chunk_relationships')
    op.drop_index(op.f('ix_chunk_relationships_source_chunk_id'), table_name='chunk_relationships')
    op.drop_table('chunk_relationships')
    op.drop_index(op.f('ix_chunk_embeddings_tenant_id'), table_name='chunk_embeddings')
    op.drop_index('ix_chunk_embeddings_tenant_hash_model_idx', table_name='chunk_embeddings')
    op.drop_index('ix_chunk_embeddings_tenant_doc_ver_idx', table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_document_version_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_content_hash'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index('ix_vector_metadata_tenant_status_idx', table_name='vector_index_metadata')
    op.drop_index('ix_vector_metadata_doc_ver_idx', table_name='vector_index_metadata')
    op.drop_index(op.f('ix_vector_index_metadata_tenant_id'), table_name='vector_index_metadata')
    op.drop_index(op.f('ix_vector_index_metadata_document_version_id'), table_name='vector_index_metadata')
    op.drop_index(op.f('ix_vector_index_metadata_document_id'), table_name='vector_index_metadata')
    op.drop_table('vector_index_metadata')
    op.drop_index(op.f('ix_embedding_jobs_tenant_id'), table_name='embedding_jobs')
    op.drop_index('ix_embedding_jobs_tenant_doc_ver_idx', table_name='embedding_jobs')
    op.drop_index('ix_embedding_jobs_tenant_created_idx', table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_document_version_id'), table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_document_id'), table_name='embedding_jobs')
    op.drop_table('embedding_jobs')
    op.drop_index(op.f('ix_document_chunks_tenant_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_version_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_workspace_domains_workspace_id'), table_name='workspace_domains')
    op.drop_table('workspace_domains')
    op.drop_index(op.f('ix_identity_providers_workspace_id'), table_name='identity_providers')
    op.drop_table('identity_providers')
    op.drop_table('domain_cooldowns')
    op.drop_index(op.f('ix_workspace_webhooks_tenant_id'), table_name='workspace_webhooks')
    op.drop_table('workspace_webhooks')
    op.drop_index(op.f('ix_vector_reindex_jobs_workspace_id'), table_name='vector_reindex_jobs')
    op.drop_table('vector_reindex_jobs')
    op.drop_index('ix_sla_logs_tenant_degraded', table_name='retrieval_sla_logs')
    op.drop_index('ix_sla_logs_tenant_created', table_name='retrieval_sla_logs')
    op.drop_index('ix_sla_logs_tenant_breach', table_name='retrieval_sla_logs')
    op.drop_index(op.f('ix_retrieval_sla_logs_tenant_id'), table_name='retrieval_sla_logs')
    op.drop_index(op.f('ix_retrieval_sla_logs_correlation_id'), table_name='retrieval_sla_logs')
    op.drop_table('retrieval_sla_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_type'), table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_tenant_id'), table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_status'), table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_next_retry_at'), table_name='notification_delivery_logs')
    op.drop_table('notification_delivery_logs')
    op.drop_index(op.f('ix_health_scan_jobs_tenant_id'), table_name='health_scan_jobs')
    op.drop_table('health_scan_jobs')
    op.drop_index('ix_circuit_events_tenant_target', table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_tenant_id'), table_name='circuit_breaker_events')
    op.drop_index(op.f('ix_circuit_breaker_events_target_module'), table_name='circuit_breaker_events')
    op.drop_table('circuit_breaker_events')
    # ### end Alembic commands ###
