"""Add F4.7 user profile fields

Revision ID: 2e2423fb5e1b
Revises: e5f6a7b8c9d0
Create Date: 2026-08-02 10:07:59.397740+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2423fb5e1b'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ff_history_flag_ws'), table_name='feature_flag_history')
    op.drop_index(op.f('ix_ff_ws_rules_workspace'), table_name='feature_flag_workspace_rules')
    op.create_index(op.f('ix_feature_flag_workspace_rules_workspace_id'), 'feature_flag_workspace_rules', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('uq_feature_flags_key'), 'feature_flags', type_='unique')
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('theme_preference', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.drop_index(op.f('idx_workspace_invitations_pending_expiry'), table_name='workspace_invitations', postgresql_where="(((status)::text = 'PENDING'::text) AND (is_deleted = false))")
    op.drop_index(op.f('idx_workspace_invitations_workspace_status_created'), table_name='workspace_invitations', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('uq_workspace_invitations_active_email'), table_name='workspace_invitations', postgresql_where="(((status)::text = 'PENDING'::text) AND (is_deleted = false))")
    op.drop_index(op.f('uq_workspace_invitations_token_hash'), table_name='workspace_invitations', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_workspace_invitations_token_hash'), 'workspace_invitations', ['token_hash'], unique=True)
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_workspace_members_keyset'), table_name='workspace_members', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_workspace_members_workspace_role'), table_name='workspace_members', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_workspace_members_workspace_status'), table_name='workspace_members', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('uq_workspace_members_active_user'), table_name='workspace_members', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_workspaces_purge_at'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspaces_purge_at'), 'workspaces', ['purge_at'], unique=False)
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.create_index(op.f('uq_workspace_members_active_user'), 'workspace_members', ['workspace_id', 'user_id'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_workspace_members_workspace_status'), 'workspace_members', ['workspace_id', 'status'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_workspace_members_workspace_role'), 'workspace_members', ['workspace_id', 'role'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_workspace_members_keyset'), 'workspace_members', ['workspace_id', 'created_at', 'id'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_token_hash'), table_name='workspace_invitations')
    op.create_index(op.f('uq_workspace_invitations_token_hash'), 'workspace_invitations', ['token_hash'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('uq_workspace_invitations_active_email'), 'workspace_invitations', ['workspace_id', sa.literal_column('lower(email::text)')], unique=True, postgresql_where="(((status)::text = 'PENDING'::text) AND (is_deleted = false))")
    op.create_index(op.f('idx_workspace_invitations_workspace_status_created'), 'workspace_invitations', ['workspace_id', 'status', 'created_at'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_workspace_invitations_pending_expiry'), 'workspace_invitations', ['status', 'expires_at'], unique=False, postgresql_where="(((status)::text = 'PENDING'::text) AND (is_deleted = false))")
    op.drop_column('users', 'version')
    op.drop_column('users', 'theme_preference')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'display_name')
    op.create_unique_constraint(op.f('uq_feature_flags_key'), 'feature_flags', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_feature_flag_workspace_rules_workspace_id'), table_name='feature_flag_workspace_rules')
    op.create_index(op.f('ix_ff_ws_rules_workspace'), 'feature_flag_workspace_rules', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_ff_history_flag_ws'), 'feature_flag_history', ['flag_id', 'workspace_id'], unique=False)
    # ### end Alembic commands ###
