"""Add tracking fields to embedding_jobs

Revision ID: 61995c415127
Revises: 5e96192505b8
Create Date: 2026-08-04 01:50:28.555136+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61995c415127'
down_revision: Union[str, None] = '5e96192505b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_jobs', sa.Column('step_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('embedding_jobs', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('embedding_jobs', sa.Column('fallback_provider', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_jobs', 'fallback_provider')
    op.drop_column('embedding_jobs', 'cancellation_reason')
    op.drop_column('embedding_jobs', 'step_metrics')
    # ### end Alembic commands ###
