"""f5.5_f5.6_versioning_and_archive

Revision ID: 1e14a3b38d04
Revises: a7ea1886faaa
Create Date: 2026-08-03 01:39:18.770557+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e14a3b38d04'
down_revision: Union[str, None] = 'a7ea1886faaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('is_active_vector', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('archived_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_documents_archived_by_user_id_users'), 'documents', 'users', ['archived_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_archived_by_user_id_users'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'archived_by_user_id')
    op.drop_column('documents', 'archived_at')
    op.drop_column('document_versions', 'is_active_vector')
    # ### end Alembic commands ###
