"""f5_1_f5_2_folders

Revision ID: ee4c9b873bce
Revises: c722fc06aec0
Create Date: 2026-08-02 14:43:39.811679+00:00

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee4c9b873bce'
down_revision: Union[str, None] = 'c722fc06aec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('depth <= 10', name=op.f('ck_folders_chk_folder_depth')),
    sa.CheckConstraint('document_count >= 0', name=op.f('ck_folders_chk_folder_document_count')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_folders_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_folders_deleted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk_folders_parent_id_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_folders_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.add_column('documents', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_documents_folder_id_folders'), 'documents', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_index('ix_folders_deleted_at', 'folders', ['workspace_id', 'deleted_at'], unique=False, postgresql_where='is_deleted = true')
    op.create_index('ix_folders_parent', 'folders', ['parent_id'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('ix_folders_workspace_root', 'folders', ['workspace_id', 'parent_id'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('ux_folders_slug_in_parent', 'folders', ['workspace_id', 'parent_id', 'slug'], unique=True, postgresql_where='is_deleted = false')
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("CREATE INDEX ix_folders_path ON folders USING GIST (path gist_trgm_ops);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_constraint(op.f('fk_documents_folder_id_folders'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'folder_id')
    op.execute("DROP INDEX IF EXISTS ix_folders_path;")
    op.drop_index('ux_folders_slug_in_parent', table_name='folders', postgresql_where='is_deleted = false')
    op.drop_index('ix_folders_workspace_root', table_name='folders', postgresql_where='is_deleted = false')
    op.drop_index('ix_folders_parent', table_name='folders', postgresql_where='is_deleted = false')
    op.drop_index('ix_folders_deleted_at', table_name='folders', postgresql_where='is_deleted = true')
    op.drop_table('folders')
    # ### end Alembic commands ###
