"""Pydantic v2 DTOs for Chunking & Document Processing (`ADR-005`)."""

from datetime import datetime
from typing import Any
import uuid

from pydantic import BaseModel, ConfigDict, Field


class ChunkDTO(BaseModel):
    """In-memory data transfer object generated by splitting strategies before persistence."""

    chunk_index: int = Field(description="Sequence order within document version")
    content: str = Field(description="NFC UTF-8 cleaned chunk text content")
    token_count: int = Field(default=0, description="Estimated or calculated token count")
    character_count: int = Field(default=0, description="Exact character count")
    page_numbers: list[int] = Field(default_factory=list, description="Origin page numbers")
    section_path: list[str] = Field(default_factory=list, description="Heading section breadcrumbs")
    metadata_json: dict[str, Any] = Field(default_factory=dict, description="Custom tags, table column headers, AST info")


class ChunkRelationshipDTO(BaseModel):
    """DTO representing a multi-parent or cross-reference link between two chunks."""

    model_config = ConfigDict(from_attributes=True)

    source_chunk_id: uuid.UUID
    target_chunk_id: uuid.UUID
    relationship_type: str
    metadata_json: dict[str, Any] | None = None


class ChunkCreateRequest(BaseModel):
    """Request DTO to trigger explicit chunking for a document."""

    strategy: str | None = Field(default=None, description="Optional override of splitting strategy")
    max_characters: int = Field(default=1000, ge=100, le=10000, description="Maximum characters per chunk")
    overlap_characters: int = Field(default=200, ge=0, le=1000, description="Overlap characters between sequential chunks")


class ChunkResponse(BaseModel):
    """Summary response DTO for a document chunk in list views."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    tenant_id: str
    document_id: uuid.UUID
    document_version_id: uuid.UUID
    chunk_index: int
    content: str
    content_hash: str
    strategy_used: str
    token_count: int
    character_count: int
    previous_chunk_id: uuid.UUID | None = None
    next_chunk_id: uuid.UUID | None = None
    parent_chunk_id: uuid.UUID | None = None
    page_numbers: list[int] | None = None
    section_path: list[str] | None = None
    is_embedded: bool = False
    created_at: datetime


class ChunkDetailResponse(ChunkResponse):
    """Comprehensive response DTO for a single chunk including metadata and graph links."""

    metadata_json: dict[str, Any] | None = None
    relationships: list[ChunkRelationshipDTO] = Field(default_factory=list)


class ChunkListResponse(BaseModel):
    """Paginated response wrapper for chunk listings."""

    items: list[ChunkResponse]
    total: int
    page: int
    size: int
    document_id: uuid.UUID
    document_version_id: uuid.UUID
    strategy_used: str | None = None


class StrategyInfoDTO(BaseModel):
    """DTO describing an available chunking strategy and its supported MIME types."""

    name: str = Field(description="Unique strategy identifier code")
    display_name: str = Field(description="Human-readable strategy name")
    description: str = Field(description="Description of the splitting logic and suitable document types")
    supported_mime_types: list[str] = Field(description="List of compatible MIME types or ['*']")
    default_max_characters: int = Field(default=1000)
    default_overlap_characters: int = Field(default=200)
    is_placeholder: bool = Field(default=False, description="True if semantic placeholder waiting for Phase 2 M2")


class ChunkMetricsDTO(BaseModel):
    """Summary metrics across chunks for a document or tenant namespace."""

    total_chunks: int
    total_characters: int
    total_tokens: int
    average_chunk_characters: float
    average_chunk_tokens: float
    strategy_breakdown: dict[str, int]
    is_embedded_count: int
