"""Veritas RAG — API schemas package."""

from .auth import AuthStatusResponse, Role, UserContext
from .common import (
                     DependencyHealth,
                     DetailedHealthResponse,
                     ErrorDetail,
                     ErrorResponse,
                     HealthStatus,
                     ResponseMetadata,
                     SuccessResponse,
)
from .errors import ErrorCode, create_error_response
from .registration import RegistrationRequest, RegistrationResponse
from .workspace_onboarding import (
    CROCKFORD_ALPHABET,
    INVITATION_TOKEN_PATTERN,
    JOIN_CODE_PATTERN,
    TENANT_UUID_PATTERN,
    WORKSPACE_ID_PATTERN,
    WORKSPACE_SLUG_PATTERN,
    JoinCodeGenerateResponse,
    JoinCodeSettingsPatchRequest,
    JoinCodeSettingsSchema,
    JoiningMode,
    JoinWorkspaceData,
    JoinWorkspaceRequest,
    JoinWorkspaceResponse,
    JoinIntentCreateRequest,
    JoinIntentCreateData,
    JoinIntentCreateResponse,
    JoinIntentPreviewData,
    JoinIntentPreviewResponse,
    OnboardingContext,
    SwitchWorkspaceData,
    SwitchWorkspaceRequest,
    SwitchWorkspaceResponse,
    WorkspacePreviewData,
    WorkspacePreviewResponse,
)

__all__ = [
    "AuthStatusResponse",
    "CROCKFORD_ALPHABET",
    "DependencyHealth",
    "DetailedHealthResponse",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "HealthStatus",
    "INVITATION_TOKEN_PATTERN",
    "JOIN_CODE_PATTERN",
    "JoinCodeGenerateResponse",
    "JoinCodeSettingsPatchRequest",
    "JoinCodeSettingsSchema",
    "JoiningMode",
    "JoinWorkspaceData",
    "JoinWorkspaceRequest",
    "JoinWorkspaceResponse",
    "JoinIntentCreateRequest",
    "JoinIntentCreateData",
    "JoinIntentCreateResponse",
    "JoinIntentPreviewData",
    "JoinIntentPreviewResponse",
    "OnboardingContext",
    "RegistrationRequest",
    "RegistrationResponse",
    "ResponseMetadata",
    "Role",
    "SuccessResponse",
    "SwitchWorkspaceData",
    "SwitchWorkspaceRequest",
    "SwitchWorkspaceResponse",
    "TENANT_UUID_PATTERN",
    "UserContext",
    "WORKSPACE_ID_PATTERN",
    "WORKSPACE_SLUG_PATTERN",
    "WorkspacePreviewData",
    "WorkspacePreviewResponse",
    "create_error_response",
]
